split:
  split_type: percent
  train_size: ~
  val_size: ~
  test_size: ~
  train_percent: 0.01
  val_percent: 0.15
  test_percent: ~
  train_examples_per_class: ~
  val_examples_per_class: ~
  test_examples_per_class: ~

norm:
  feat_norm: false
  adj_norm: false

modify:
  add_self_loop: false
  from_npz_largest_component: false

